image:
  name: thetelematic95/monkey
  tag: 0.0.12

ingress:
  enabled: true
  ingressClassName: ngrok
  host: frankly-unbiased-shark.ngrok-free.app

config:
  LLM_ENGINE: openai

api:
  replicas:
    min: 2
    max: 3

consumers:
  translations:
    replicas:
      min: 1
      max: 2
  summaries:
    replicas:
      min: 1
      max: 2
