---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: infra
spec:
  interval: 1m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: infra
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: keda
      version: 2.14.2
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: infra
      interval: 5m
  releaseName: keda
  targetNamespace: infra
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values: {}
