---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bitnami
  namespace: infra
spec:
  interval: 5m
  url: https://github.com/bitnami/charts
  ref:
    commit: 73bdc544c5046bc75dfb855a21939219ca929852
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: infra
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: bitnami/kube-prometheus
      version: 9.5.4
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: infra
      interval: 5m
  releaseName: kube-prometheus
  targetNamespace: infra
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    alertmanager:
      enabled: false
    
    prometheus:
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          memory: 2Gi
        limits:
          memory: 3Gi
