---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kube-prometheus
  namespace: infra
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/kube-prometheus
  ref:
    tag: 9.5.4
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: infra
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus
    namespace: infra
  releaseName: kube-prometheus
  targetNamespace: infra
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    alertmanager:
      enabled: false
    
    prometheus:
      persistence:
        enabled: true
        size: 20Gi
      resources:
        requests:
          memory: 2Gi
        limits:
          memory: 3Gi
