apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: monkey
  namespace: flux-system
spec:
  image: thetelematic95/monkey
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: monkey
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: monkey
  policy:
    semver:
      range: x.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: monkey
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@doesntexist.local
        name: Flux
      messageTemplate: 'RASPBERRY DEPLOY MONKEY: {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
  update:
    path: ./kubernetes/clusters/raspberry/monkey.yaml
    strategy: Setters
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monkey
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kubernetes/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  releaseName: monkey
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    image:
      name: thetelematic95/monkey
      tag: 0.0.33 # {"$imagepolicy": "flux-system:monkey:tag"}
    ingress:
      enabled: true
      ingressClassName: ngrok
      hostname: ghoul-happy-evidently.ngrok-free.app
    api:
      replicas:
        min: 2
        max: 3
    consumers:
      translations:
        replicas:
          min: 1
          max: 2
      summaries:
        replicas:
          min: 1
          max: 2
