---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monkey
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/TheTelematic/monkey
  ref:
    branch: main
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: monkey
  namespace: flux-system
spec:
  image: thetelematic95/monkey
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: monkey
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: monkey
  policy:
    semver:
      range: x.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: monkey
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: monkey
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: arturoteleco95@protonmail.ch
        name: Flux
      messageTemplate: 'RASPBERRY DEPLOY MONKEY: {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: ./kubernetes/clusters/raspberry/monkey.yaml
    strategy: Setters
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monkey
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kubernetes/chart
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: monkey
        namespace: flux-system
      interval: 5m
  releaseName: monkey
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    image:
      name: thetelematic95/monkey
      tag: 0.0.14  # {"$imagepolicy": "flux-system:monkey"}

    ingress:
      enabled: true
      ingressClassName: ngrok
      host: frankly-unbiased-shark.ngrok-free.app

    config:
      LLM_ENGINE: openai

    api:
      replicas:
        min: 2
        max: 3

    consumers:
      translations:
        replicas:
          min: 1
          max: 2

      summaries:
        replicas:
          min: 1
          max: 2
