image:
  name: thetelematic95/monkey
  tag: 0.0.5

ingress:
  ingressClassName: ngrok
  host: frankly-unbiased-shark.ngrok-free.app

config:
  LLM_ENGINE: openai

api:
  replicas:
    min: 2
    max: 3
