---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ngrok-ingress-controller
  namespace: infra
spec:
  interval: 5m0s
  url: https://github.com/ngrok/kubernetes-ingress-controller
  ref:
    tag: helm-chart-0.14.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngrok-ingress-controller
  namespace: infra
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: helm/ingress-controller
      version: 0.14.0
      sourceRef:
        kind: GitRepository
        name: ngrok-ingress-controller
        namespace: infra
      interval: 5m
  releaseName: ngrok-ingress-controller
  targetNamespace: infra
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    nameOverride: ngrok-ingress-controller
    fullnameOverride: ngrok-ingress-controller
