apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  VERSION: "{{ .Values.image.tag }}"
  DOMAIN_HOST: "{{ .Values.ingress.host }}"
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
