apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  endpoints:
    - port: {{ .Values.service.port.name }}
---
{{- range $key, $value := .Values.consumers }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}-consumer-{{ $key }}
  labels:
    app: {{ $.Release.Name }}-consumer-{{ $key }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-consumer-{{ $key }}
  endpoints:
    - port: {{ $.Values.service.port.name }}
{{- end }}
