apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port.port }}
      targetPort: {{ .Values.service.port.name }}
      name: {{ .Values.service.port.name }}
  