image:
  name: monkey
  tag: latest
  policy: IfNotPresent

secretName: monkey

api:
  terminationGracePeriodSeconds: 60  # It has to be greater than Prometheus scrape interval
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 256Mi

consumers:
  translations:
    terminationGracePeriodSeconds: 60  # It has to be greater than Prometheus scrape interval
    keda:
      queue: &translationsQueue monkey.translations
      minMessagesToScaleUp: 1
    replicas:
      min: 0
      max: 1
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 256Mi
  summaries:
    terminationGracePeriodSeconds: 60  # It has to be greater than Prometheus scrape interval
    keda:
      queue: &summariesQueue monkey.summaries
      minMessagesToScaleUp: 1
    replicas:
      min: 0
      max: 1
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 256Mi

service:
  port:
    container: 8000
    name: http
    port: 80

ingress:
  enabled: false
  ingressClassName: ""
  host: ""

config:
  LOG_LEVEL: "INFO"
  OPENAI_API_KEY: ""
  REDIS_HOST: "redis-master.infra.svc.cluster.local"
  CACHE_EXPIRATION_SECONDS: "3600"
  RABBITMQ_URL: "amqp://monkey:monkey@rabbitmq.infra.svc.cluster.local:5672/"  # It should go with a Secret/SealedSecret
  RABBITMQ_URL_HTTP: "http://monkey:monkey@rabbitmq.infra.svc.cluster.local:15672/"  # It should go with a Secret/SealedSecret
  RABBITMQ_QUEUE_TRANSLATIONS: *translationsQueue
  RABBITMQ_QUEUE_SUMMARIES: *summariesQueue
  READINESS_CONSUMERS_FILE: "/tmp/ready"
  LIVENESS_CONSUMERS_FILE: "/tmp/live"
  PROMETHEUS_INTERVAL: "30"
  API_GRACEFUL_SHUTDOWN_TIMEOUT: "50"  # Less than api.terminationGracePeriodSeconds
  APIFY_CONTENT_CRAWLER_URL: "https://www.techradar.com/news/best-phone"
  PINECONE_INDEX_NAME: "monkey"
