image:
  name: monkey
  tag: latest
  policy: IfNotPresent


replicas:
  api:
    min: 1
  consumers:
    translations:
      min: 1

service:
  port:
    container: 8000
    name: http
    port: 80

ollama:
  enabled: false
  port: 11434
  image:
    name: ollama/ollama
    tag: 0.1.36
    policy: IfNotPresent

config:
  LOG_LEVEL: "INFO"
  OLLAMA_URL: ""
  OPENAI_API_KEY: ""
  LLM_ENGINE: ""
  REDIS_HOST: "redis-master"
  RABBITMQ_URL: "amqp://monkey:monkey@rabbitmq:5672/"  # It should go with a Secret/SealedSecret

ingress:
  enabled: true
  hostname: "monkey.local"

consumers:
  translations:
    replicas:
      min: 1
      max: 1
