image:
  name: monkey
  tag: latest
  policy: IfNotPresent


replicas:
  min: 1

service:
  port:
    container: 8000
    name: http
    port: 80

ollama:
  enabled: false
  image:
    name: ollama/ollama
    tag: 0.1.36
    policy: IfNotPresent
  port: 11434
