ingress:
  enabled: true
  hostname: grafana.local
  ingressClassName: nginx

datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated:9090
        access: proxy
        isDefault: true
