ingress:
  enabled: true
  ingressClassName: nginx
  host: monkey.local

config:
  CACHE_EXPIRATION_SECONDS: "300" # 5 minutes
  LOG_LEVEL: "INFO"

consumers:
  translations:
    replicas:
      min: 1
      max: 1
  summaries:
    replicas:
      min: 1
      max: 1
