apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      name: {{ .Release.Name }}-api
      labels:
        app: {{ .Release.Name }}-api
    spec:
      terminationGracePeriodSeconds: {{ .Values.api.terminationGracePeriodSeconds }}
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-api
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.policy }}
          command:
            - /bin/sh
            - -c
          args:
            - python main.py api
          ports:
            - containerPort: {{ .Values.service.port.container }}
              name: {{ .Values.service.port.name }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/probes/liveness
              port: {{ .Values.service.port.container }}
          readinessProbe:
            httpGet:
              path: /api/probes/readiness
              port: {{ .Values.service.port.container }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
---
