---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ .Release.Name }}-api
    minReplicas: {{ .Values.api.replicas.min }}
    maxReplicas: {{ .Values.api.replicas.max }}
    targetCPUUtilizationPercentage: 80
---
{{- range $key, $value := $.Values.consumers }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $.Release.Name }}-consumer-{{ $key }}
spec:
  scaleTargetRef:
    name: {{ $.Release.Name }}-consumer-{{ $key }}
  minReplicaCount: {{ $value.replicas.min }}
  maxReplicaCount: {{ $value.replicas.max }}
  triggers:
  - type: rabbitmq
    metadata:
      queueName: {{ $value.keda.queue }}
      mode: QueueLength
      value: {{ $value.keda.minMessagesToScaleUp | quote }}
      hostFromEnv: RABBITMQ_URL_HTTP
---
{{- end }}
