{{- range $key, $value := $.Values.consumers }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $.Release.Name }}-consumer-{{ $key }}
spec:
  scaleTargetRef:
    name: {{ $.Release.Name }}-consumer-{{ $key }}
  minReplicaCount: {{ $value.replicas.min }}
  maxReplicaCount: {{ $value.replicas.max }}
  triggers:
  - type: rabbitmq
    metadata:
      queueName: {{ $value.keda.queue }}
      mode: QueueLength
      value: {{ $value.keda.minMessagesToScaleUp | quote }}
      hostFromEnv: RABBITMQ_URL_HTTP
---
{{- end }}
