import os

APP_NAME = "monkey"
VERSION = os.getenv("VERSION")
DOMAIN_HOST = os.getenv("DOMAIN_HOST")

POD_IP = os.getenv("POD_IP")
API_GRACEFUL_SHUTDOWN_TIMEOUT = int(os.getenv("API_GRACEFUL_SHUTDOWN_TIMEOUT", 30))

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
SERVICE_PORT = os.getenv("SERVICE_PORT", 8000)

OLLAMA_URL = os.getenv("OLLAMA_URL")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
LLM_ENGINE = os.getenv("LLM_ENGINE", "openai")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
REDIS_DB_QUERIES = int(os.getenv("REDIS_DB_QUERIES", 0))
REDIS_DB_TRANSLATIONS = int(os.getenv("REDIS_DB_TRANSLATIONS", 1))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
CACHE_EXPIRATION_SECONDS = int(os.getenv("CACHE_EXPIRATION_SECONDS", 300))

RABBITMQ_URL = os.getenv("RABBITMQ_URL")
RABBITMQ_PREFETCH_COUNT = int(os.getenv("RABBITMQ_PREFETCH_COUNT", 10))
RABBITMQ_QUEUE_TRANSLATIONS = os.getenv("RABBITMQ_QUEUE_TRANSLATIONS", "monkey.translations")

LIVENESS_CONSUMERS_FILE = os.getenv("LIVENESS_CONSUMERS_FILE")
LIVENESS_CONSUMERS_SLEEP_TIME = int(os.getenv("LIVENESS_CONSUMERS_SLEEP_TIME", 5))

READINESS_CONSUMERS_FILE = os.getenv("READINESS_CONSUMERS_FILE")
READINESS_CONSUMERS_SLEEP_TIME = int(os.getenv("READINESS_CONSUMERS_SLEEP_TIME", 5))

PROMETHEUS_INTERVAL = int(os.getenv("PROMETHEUS_INTERVAL", 5))
